/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const userScenes = new Collection({
      id: "pbc_user_scenes",
      name: "user_scenes",
      type: "base",
      system: false,
      listRule: "@request.auth.id = user_id",
      viewRule: "@request.auth.id = user_id",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id = user_id",
      deleteRule: "@request.auth.id = user_id",
      indexes: [
        "CREATE INDEX `idx_user_scenes_user_id` ON `user_scenes` (`user_id`)",
        "CREATE UNIQUE INDEX `idx_user_scenes_user_room` ON `user_scenes` (`user_id`, `room_id`)",
      ],
      fields: [
        {
          id: "field_us_user_id",
          name: "user_id",
          type: "text",
          system: false,
          primaryKey: false,
          required: true,
          presentable: false,
          hidden: false,
          min: 1,
          max: 0,
          pattern: "",
          autogeneratePattern: "",
        },
        {
          id: "field_us_room_id",
          name: "room_id",
          type: "text",
          system: false,
          primaryKey: false,
          required: true,
          presentable: false,
          hidden: false,
          min: 1,
          max: 0,
          pattern: "",
          autogeneratePattern: "",
        },
        {
          id: "field_us_room_key",
          name: "room_key",
          type: "text",
          system: false,
          primaryKey: false,
          required: true,
          presentable: false,
          hidden: true,
          min: 1,
          max: 0,
          pattern: "",
          autogeneratePattern: "",
        },
        {
          id: "field_us_name",
          name: "name",
          type: "text",
          system: false,
          primaryKey: false,
          required: true,
          presentable: true,
          hidden: false,
          min: 1,
          max: 200,
          pattern: "",
          autogeneratePattern: "",
        },
        {
          id: "field_us_type",
          name: "type",
          type: "select",
          system: false,
          primaryKey: false,
          required: true,
          presentable: false,
          hidden: false,
          maxSelect: 1,
          values: ["own", "joined"],
        },
        {
          id: "field_us_last_visited_at",
          name: "last_visited_at",
          type: "date",
          system: false,
          primaryKey: false,
          required: false,
          presentable: false,
          hidden: false,
          min: "",
          max: "",
        },
      ],
    });
    app.save(userScenes);
  },

  (app) => {
    try {
      app.delete(app.findCollectionByNameOrId("user_scenes"));
    } catch (_) {}
  },
);
